DROP TABLE report;

CREATE TABLE report (
  id INT PRIMARY KEY AUTO_INCREMENT,
  rqst_date DATE,
  rqst_field varchar(10),
  rqst_cpst varchar(10),
  rqst_method varchar(15),
  fpno INT,
  task_division_lrg varchar(20),
  task_division_mid varchar(50),
  task_process_l1 varchar(40),
  task_process_l2 varchar(40),
  task_process_l3 varchar(40),
  hm_menu_title varchar(40),
  rqst_title varchar(200),
  task_type1 varchar(100),
  task_type2 varchar(100),
  status VARCHAR(50),
  damdangja VARCHAR(50),
  yocheongilja VARCHAR(20),
  yocheongdate VARCHAR(20),
  wanryodate VARCHAR(50),
  wanryosigan VARCHAR(50),
  soyoil INT,
  soyosigan INT,
  nanido VARCHAR(2),
  cheoritotal INT,
  carryover VARCHAR(100),
  comment VARCHAR(300)
);

INSERT INTO report (
  rqst_date,
  rqst_field,
  rqst_cpst,
  rqst_method,
  fpno,
  task_division_lrg,
  task_division_mid,
  task_process_l1,
  task_process_l2,
  task_process_l3,
  hm_menu_title,
  rqst_title,
  task_type1,
  task_type2,
  status,
  damdangja,
  yocheongilja,
  yocheongdate,
  wanryodate,
  wanryosigan,
  soyoil,
  soyosigan,
  nanido,
  cheoritotal,
  carryover,
  comment
) VALUES
(
  '2022-03-25',
  '김아빈',
  '김아빈',
  'SR요청서',
  338,
  '홈페이지',
  '홈페이지 관련 정책',
  '(청년)내일체움공제',
  '홈피 및 기타',
  '개인/기업 회원가입',
  '홈페이지 리뉴얼',
  '청년내일채움공제 관리자홈페이지(HCMS) 크롬 브라우저 전환 작업 요청',
  '기능개선',
  '성능개선',
  '진행중',
  '신창민',
  '2022-03-25',
  '오전 9:00',
  '진행중',
  '진행중',
  3,
  0,
  '상',
  24,
  '',
  '개발자 분석중'
), (
  '2022-03-31',
  '김아빈',
  '김아빈',
  'E-MAIL',
  55,
  '홈페이지',
  '마이페이지 회원정보관리',
  '(청년)내일체움공제',
  '청약신청',
  '개인/기업 회원가입',
  '홈페이지 리뉴얼',
  '간편인증 전자서명 수정 요청',
  '기능개선',
  '성능개선',
  '완료',
  '신창민',
  '2022-03-31',
  '오전 9:00',
  '진행중',
  '진행중',
  1,
  0,
  '상',
  8,
  '',
  '솔류션 업체요청(라온시큐어)'
),
(
'2022.03.21',
    "김민영",
    "정유정",
    "SR요청서",
    325,
    "홈페이지",
    "이메일",
    "내일채움공제",
    "홈피 및 기타",
    null,
    "E_MAIL",
    "미납안내문 관련 문의",
    "문의 ",
    "성능개선",
    "완료",
    "신창민",
    44643,
    0.375,
    44651,
    0.5833333333333334,
    8,
    null,
    "하",
    64,
    null,
    "진행중(자동메일 양식 업로드 요청 후 대기중)"
);